name: Create Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

  release:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }}"
      - run: echo "${{ steps.package-version.outputs.current-version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('{0}{1}', 'v', steps.package-version.outputs.current-version) }}
          release_name: Release ${{ format('{0}{1}', 'v', steps.package-version.outputs.current-version) }}
          draft: false
          prerelease: false
        if: ${{ github.ref == join('refs/tags/v', steps.package-version.outputs.current-version) }}
